### ISSUE TITLE
python bindings for mujoco

### ISSUE THREAD

**Issue by huiwenzhang** [ywchao/merel-mocap-gail#1]
Hi, 
Thanks for posting this package. Before diving into the codes, I want to know whether the mujoco-py is necessary for running this package? Cause you used both baselines and dm_control, I think both of them implemented a wrapper for mujoco. According to the paper, they seems to use the dm_control version mujoco.
Thanks in advance.

**Comment by ywchao** [comment]
mujoco-py is **not** needed for running this package. I suppose you ran into trouble installing mujoco-py because it is considered a dependency of baselines and will be automatically installed when you install baselines with pip. You can simply disable that by making the following change to `baselines/setup.py` before running pip install:

```
-   'gym[mujoco,atari,classic_control,robotics]',
+   'gym[atari,classic_control,robotics]', 
```

This will avoid installing mujoco-py and everything should still work.

As a side note, the package is tested with an old version of dm_control. I've added that version as a submodule and updated README. Newer versions might work as well, but we've not tested that.
